name: Bug report
description: Report a bug with the WordPress block editor or Gutenberg plugin
title: '<title>'
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! If this is a security issue, please report it in HackerOne instead: https://hackerone.com/wordpress
    - type: textarea
      attributes:
          label: Description and step-by-step reproduction instructions
          description: Please write a brief description of the bug and the steps needed to reproduce it, including what you expect to happen and what is currently happening.
          placeholder: |
              Feature '...' is not working properly because '...'. Steps to reproduce:
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. I expect '...' to happen, but '...' happens instead
      validations:
          required: true

  
    - type: checkboxes
      attributes:
          label: Pre-checks
          description: Please check if the bug has already been reported by searching https://github.com/WordPress/gutenberg/issues and make sure before reporting the bug is neither related to another plugin nor theme specific.
          options:
              - label: I have searched the existing issues.
              - label: I have tested with all plugins deactivated except Gutenberg.
              - label: I have tested with a default theme.
